/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  ClusterFilter,
  Context,
  Program,
  PublicKey,
} from '@metaplex-foundation/umi';
import {
  getMintCraftNftProgramErrorFromCode,
  getMintCraftNftProgramErrorFromName,
} from '../errors';

export const MINT_CRAFT_NFT_PROGRAM_PROGRAM_ID =
  'FqDJgJMNxGqpR8p3A7mtp4Cyow2DiXrXFoGCL1RXYsvU' as PublicKey<'FqDJgJMNxGqpR8p3A7mtp4Cyow2DiXrXFoGCL1RXYsvU'>;

export function createMintCraftNftProgramProgram(): Program {
  return {
    name: 'mintCraftNftProgram',
    publicKey: MINT_CRAFT_NFT_PROGRAM_PROGRAM_ID,
    getErrorFromCode(code: number, cause?: Error) {
      return getMintCraftNftProgramErrorFromCode(code, this, cause);
    },
    getErrorFromName(name: string, cause?: Error) {
      return getMintCraftNftProgramErrorFromName(name, this, cause);
    },
    isOnCluster() {
      return true;
    },
  };
}

export function getMintCraftNftProgramProgram<T extends Program = Program>(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): T {
  return context.programs.get<T>('mintCraftNftProgram', clusterFilter);
}

export function getMintCraftNftProgramProgramId(
  context: Pick<Context, 'programs'>,
  clusterFilter?: ClusterFilter
): PublicKey {
  return context.programs.getPublicKey(
    'mintCraftNftProgram',
    MINT_CRAFT_NFT_PROGRAM_PROGRAM_ID,
    clusterFilter
  );
}
