/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type InitializeConfigInstructionAccounts = {
  signer: Signer;
  config?: PublicKey | Pda;
  systemProgram?: PublicKey | Pda;
};

// Data.
export type InitializeConfigInstructionData = {
  discriminator: Uint8Array;
  platformFees: number;
};

export type InitializeConfigInstructionDataArgs = { platformFees: number };

export function getInitializeConfigInstructionDataSerializer(): Serializer<
  InitializeConfigInstructionDataArgs,
  InitializeConfigInstructionData
> {
  return mapSerializer<
    InitializeConfigInstructionDataArgs,
    any,
    InitializeConfigInstructionData
  >(
    struct<InitializeConfigInstructionData>(
      [
        ['discriminator', bytes({ size: 8 })],
        ['platformFees', u8()],
      ],
      { description: 'InitializeConfigInstructionData' }
    ),
    (value) => ({
      ...value,
      discriminator: new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]),
    })
  ) as Serializer<
    InitializeConfigInstructionDataArgs,
    InitializeConfigInstructionData
  >;
}

// Args.
export type InitializeConfigInstructionArgs =
  InitializeConfigInstructionDataArgs;

// Instruction.
export function initializeConfig(
  context: Pick<Context, 'eddsa' | 'programs'>,
  input: InitializeConfigInstructionAccounts & InitializeConfigInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'mintCraftNftProgram',
    'BrrVsyYH1Ght4cZwZYuWNY7659skft5wYHYrxPndgKQv'
  );

  // Accounts.
  const resolvedAccounts = {
    signer: {
      index: 0,
      isWritable: true as boolean,
      value: input.signer ?? null,
    },
    config: {
      index: 1,
      isWritable: true as boolean,
      value: input.config ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: InitializeConfigInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.config.value) {
    resolvedAccounts.config.value = context.eddsa.findPda(programId, [
      bytes().serialize(new Uint8Array([99, 111, 110, 102, 105, 103])),
    ]);
  }
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getInitializeConfigInstructionDataSerializer().serialize(
    resolvedArgs as InitializeConfigInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
